### ISSUE TITLE
Creating a Service Account fails

### ISSUE THREAD

**Issue by slaskawi** [fusor/ansible-playbook-bundle#118]
When I try to create a Service Account using the following snippet:

```
- name: Create Service Account
  k8s_v1_service_account:
    name: '{{ application_name }}'
    namespace: '{{ namespace }}'
```

I get an error:

```
$ oc run apb-test --image=jboss-dataservices/datagrid-online-services-dev --restart=Never --attach=true -- provision -vvvvv -e namespace=myproject
If you don't see a command prompt, try pressing enter.
+ [[ provision -vvvvv -e namespace=myproject == *\s\2\i\/\a\s\s\e\m\b\l\e* ]]
+ ACTION=provision
+ shift
+ playbooks=/opt/apb/actions
+ CREDS=/var/tmp/bind-creds
+ TEST_RESULT=/var/tmp/test-result
+ whoami
+ '[' -w /etc/passwd ']'
++ id -u
+ echo 'apb:x:1000060000:0:apb user:/opt/apb:/sbin/nologin'
+ oc-login.sh
Attempting to login with a service account...
Logged into "https://kubernetes.default:443" as "system:serviceaccount:myproject:default" using the token provided.
You have one project on this server: "myproject"
+ set +x
Using project "myproject".
Welcome! See 'oc help' to get started.
ls: cannot access /etc/apb-secrets: No such file or directory
+ [[ -e /opt/apb/actions/provision.yaml ]]
+ [[ -e /opt/apb/actions/provision.yml ]]
+ ANSIBLE_ROLES_PATH=/etc/ansible/roles:/opt/ansible/roles
+ ansible-playbook /opt/apb/actions/provision.yml -vvvvv -e namespace=myproject
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
 [WARNING]: provided hosts list is empty, only localhost is available
PLAYBOOK: provision.yml ********************************************************
1 plays in /opt/apb/actions/provision.yml
PLAY [datagrid-online-services-apb playbook to provision the application] ******
META: ran handlers
TASK [ansible.kubernetes-modules : Install latest openshift client] ************
task path: /etc/ansible/roles/ansible.kubernetes-modules/tasks/main.yml:4
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}
TASK [ansibleplaybookbundle.asb-modules : debug] *******************************
task path: /etc/ansible/roles/ansibleplaybookbundle.asb-modules/tasks/main.yml:2
ok: [localhost] => {
    "msg": "Ansible Service Broker modules loaded"
}
TASK [provision-datagrid-online-services-apb : Create Service Account] *********
task path: /opt/ansible/roles/provision-datagrid-online-services-apb/tasks/main.yml:4
Using module file /etc/ansible/roles/ansible.kubernetes-modules/library/k8s_v1_service_account.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: apb
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /opt/apb/.ansible/tmp/ansible-tmp-1506327197.18-130421672005838 `" && echo ansible-tmp-1506327197.18-130421672005838="` echo /opt/apb/.ansible/tmp/ansible-tmp-1506327197.18-130421672005838 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpkaWZWz TO /opt/apb/.ansible/tmp/ansible-tmp-1506327197.18-130421672005838/k8s_v1_service_account.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /opt/apb/.ansible/tmp/ansible-tmp-1506327197.18-130421672005838/ /opt/apb/.ansible/tmp/ansible-tmp-1506327197.18-130421672005838/k8s_v1_service_account.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /opt/apb/.ansible/tmp/ansible-tmp-1506327197.18-130421672005838/k8s_v1_service_account.py; rm -rf "/opt/apb/.ansible/tmp/ansible-tmp-1506327197.18-130421672005838/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_EeOs1k/ansible_module_k8s_v1_service_account.py", line 370, in <module>
    main()
  File "/tmp/ansible_EeOs1k/ansible_module_k8s_v1_service_account.py", line 364, in main
    module.execute_module()
  File "/tmp/ansible_EeOs1k/ansible_modlib.zip/ansible/module_utils/k8s_common.py", line 199, in execute_module
  File "/tmp/ansible_EeOs1k/ansible_modlib.zip/ansible/module_utils/k8s_common.py", line 251, in _create
  File "/usr/lib/python2.7/site-packages/openshift/helper/base.py", line 242, in create_object
    return_obj = self._wait_for_response(name, namespace, 'create')
  File "/usr/lib/python2.7/site-packages/openshift/helper/base.py", line 493, in _wait_for_response
    elif obj and obj.status and hasattr(obj.status, 'phase'):
AttributeError: 'V1ServiceAccount' object has no attribute 'status'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_EeOs1k/ansible_module_k8s_v1_service_account.py\", line 370, in <module>\n    main()\n  File \"/tmp/ansible_EeOs1k/ansible_module_k8s_v1_service_account.py\", line 364, in main\n    module.execute_module()\n  File \"/tmp/ansible_EeOs1k/ansible_modlib.zip/ansible/module_utils/k8s_common.py\", line 199, in execute_module\n  File \"/tmp/ansible_EeOs1k/ansible_modlib.zip/ansible/module_utils/k8s_common.py\", line 251, in _create\n  File \"/usr/lib/python2.7/site-packages/openshift/helper/base.py\", line 242, in create_object\n    return_obj = self._wait_for_response(name, namespace, 'create')\n  File \"/usr/lib/python2.7/site-packages/openshift/helper/base.py\", line 493, in _wait_for_response\n    elif obj and obj.status and hasattr(obj.status, 'phase'):\nAttributeError: 'V1ServiceAccount' object has no attribute 'status'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
	to retry, use: --limit @/opt/apb/actions/provision.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

+ EXIT_CODE=2
+ set +ex
+ '[' -f /var/tmp/test-result ']'
+ '[' -f /var/tmp/bind-creds ']'
+ exit 2
pod myproject/apb-test terminated (Error)
make: *** [Makefile:146: test-apb-provision] Error 2
```

The fun part is that the SA has actually been created:

```
$ oc get sa                                                                                                                                                                    
NAME              SECRETS   AGE
builder           2         3m
caching-service   2         2m
default           2         3m
deployer          2         3m
```

**Comment by rthallisey** [comment]
This is an issue with the ansible kubernetes module. @fabianvf can you port this issue over to that repo? Closing it here.
