### ISSUE TITLE
Failed to install APB from source

### ISSUE THREAD

**Issue by jianzhangbjz** [fusor/ansible-playbook-bundle#137]
Hi,

I followed the [installing-from-source](https://github.com/ansibleplaybookbundle/ansible-playbook-bundle#installing-from-source) docs, but I got errors when executing `pip install -r src/requirements.txt`command.
Errors as the following, could you help to check it? Or something else I missed?
```
(apb)[root@ip-172-18-3-39 ansible-playbook-bundle]# pip install -r src/requirements.txt 
Downloading/unpacking PyYAML<4.0,>=3.10 (from -r src/requirements.txt (line 1))
  Downloading PyYAML-3.12.tar.gz (253kB): 253kB downloaded
  Running setup.py egg_info for package PyYAML
Downloading/unpacking docker<3.0.0,>=2.1.0 (from -r src/requirements.txt (line 2))
  Downloading docker-2.5.1.tar.gz (155kB): 155kB downloaded
  Running setup.py egg_info for package docker
Downloading/unpacking openshift>=0.0.1 (from -r src/requirements.txt (line 3))
  Downloading openshift-0.3.2.tar.gz (298kB): 298kB downloaded
  Running setup.py egg_info for package openshift
Downloading/unpacking Jinja2>=2.7.2 (from -r src/requirements.txt (line 4))
  Downloading Jinja2-2.9.6.tar.gz (437kB): 437kB downloaded
  Running setup.py egg_info for package Jinja2
    warning: no files found matching 'run-tests.py'
    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no files found matching '*' under directory 'jinja2/testsuite/res'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
Downloading/unpacking requests>=2.6.0 (from -r src/requirements.txt (line 5))
  Downloading requests-2.18.4.tar.gz (126kB): 126kB downloaded
  Running setup.py egg_info for package requests
    warning: no files found matching 'NOTICE'
Downloading/unpacking ruamel.yaml>=0.15 (from -r src/requirements.txt (line 6))
  Downloading ruamel.yaml-0.15.34.tar.gz (260kB): 260kB downloaded
  Running setup.py egg_info for package ruamel.yaml
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /tmp/apb/lib/python2.7/site-packages (from docker<3.0.0,>=2.1.0->-r src/requirements.txt (line 2))
Downloading/unpacking websocket-client>=0.32.0 (from docker<3.0.0,>=2.1.0->-r src/requirements.txt (line 2))
  Downloading websocket_client-0.44.0.tar.gz (194kB): 194kB downloaded
  Running setup.py egg_info for package websocket-client
Downloading/unpacking docker-pycreds>=0.2.1 (from docker<3.0.0,>=2.1.0->-r src/requirements.txt (line 2))
  Downloading docker-pycreds-0.2.1.tar.gz
  Running setup.py egg_info for package docker-pycreds
Downloading/unpacking dictdiffer (from openshift>=0.0.1->-r src/requirements.txt (line 3))
  Downloading dictdiffer-0.6.1.tar.gz
  Running setup.py egg_info for package dictdiffer
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/apb/build/dictdiffer/.eggs/pytest_runner-2.12.1-py2.7.egg
Downloading/unpacking kubernetes~=3.0.0 (from openshift>=0.0.1->-r src/requirements.txt (line 3))
  Downloading kubernetes-3.0.0.tar.gz (328kB): 328kB downloaded
  Running setup.py egg_info for package kubernetes
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/apb/build/kubernetes/setup.py", line 30, in <module>
        with open('requirements.txt') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/apb/build/kubernetes/setup.py", line 30, in <module>

    with open('requirements.txt') as f:

IOError: [Errno 2] No such file or directory: 'requirements.txt'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/apb/build/kubernetes
Storing complete log in /root/.pip/pip.log
(apb)[root@ip-172-18-3-39 ansible-playbook-bundle]# python
Python 2.7.5 (default, May  3 2017, 07:55:04) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-14)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
(apb)[root@ip-172-18-3-39 ansible-playbook-bundle]# cat src/requirements.txt 
PyYAML>=3.10,<4.0
docker>=2.1.0,<3.0.0
openshift>=0.0.1
Jinja2>=2.7.2
requests>=2.6.0
ruamel.yaml>=0.15
(apb)[root@ip-172-18-3-39 ansible-playbook-bundle]# pwd
/root/ansible-playbook-bundle
(apb)[root@ip-172-18-3-39 ansible-playbook-bundle]# uname -a
Linux ip-172-18-3-39.ec2.internal 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
(apb)[root@ip-172-18-3-39 ansible-playbook-bundle]# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.4 (Maipo)
Release:	7.4
Codename:	Maipo

```

**Comment by mhrivnak** [comment]
Thanks for the bug report, and especially for including all the info about your environment! It looks like this was a bug in the kubernetes python library that has since been fixed: https://github.com/kubernetes-incubator/client-python/issues/373

But, it still affects apb users because we have the version pinned to 3.0.0.

As a workaround, if you use a newer version of pip, it will install a "wheel" instead of an "egg", and the wheel does not exhibit this problem. I suggest adding a ``pip install -U pip`` after activating the virtualenv.

Incidentally, Fedora already has a new-enough version of pip that it installs the wheel by default.

**Comment by jianzhangbjz** [comment]
Thanks for your clear explanation! I will have a try later.

**Comment by dymurray** [comment]
Closing this issue since the kubernetes client bug has been resolved..
