### ISSUE TITLE
apb busted when run from rpm build

### ISSUE THREAD

**Issue by jmrodri** [fusor/ansible-playbook-bundle#15]
`tito build --test --rpm -i` will work but the resulting apb tool fails to run.

```
[jesusr@speed3 ansible-playbook-bundle{master}]$ apb init --help
Traceback (most recent call last):
  File "/usr/bin/apb", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2958, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2944, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2971, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'docker==2.2.1' distribution was not found and is required by apb
```

The problem is the `src/requirements.txt` lists `docker==2.2.1` but there is no python-docker in Fedora 25. The apb.spec has the wrong `Requires: docker`, I thought we required DOCKER, but we need `python-docker`. 

Fedora 25 has `python-docker-py` version 1.10.6.
Fedora 26 has `python-docker-py` version 1.10.6 **and**
`python-docker` version 2.2.1.

We need to be careful with willy nilly pulling in dependencies using pip without first checking to see if there is a packaged version for our target OSes: Fedora, CentOS, RHEL.

**Comment by jmontleon** [comment]
I think this has been fixed for awhile.

On a clean system:
```
[root@localhost ~]# sudo dnf -y copr enable @ansible-service-broker/ansible-service-broker
Repository successfully enabled.
[root@localhost ~]# sudo dnf -y install apb
Last metadata expiration check: 0:08:12 ago on Tue Jun  6 13:33:07 2017.
Dependencies resolved.
=================================================================================================================================================================================================================================================================
 Package                                                            Arch                                  Version                                                       Repository                                                                          Size
=================================================================================================================================================================================================================================================================
Installing:
 PyYAML                                                             x86_64                                3.11-13.fc25                                                  fedora                                                                             170 k
 apb                                                                noarch                                0.1.1-1.20170606172632.fc25                                   group_ansible-service-broker-ansible-service-broker                                 24 k
 audit-libs-python3                                                 x86_64                                2.7.6-1.fc25                                                  updates                                                                             78 k
 checkpolicy                                                        x86_64                                2.5-8.fc25                                                    fedora                                                                             297 k
 container-selinux                                                  noarch                                2:2.14-1.fc25                                                 updates                                                                             32 k
 docker                                                             x86_64                                2:1.12.6-6.gitae7d637.fc25                                    updates                                                                             17 M
 docker-common                                                      x86_64                                2:1.12.6-6.gitae7d637.fc25                                    updates                                                                             71 k
 gnupg                                                              x86_64                                1.4.21-1.fc25                                                 fedora                                                                             1.3 M
 libcgroup                                                          x86_64                                0.41-9.fc25                                                   fedora                                                                              67 k
 libsemanage-python3                                                x86_64                                2.5-9.fc25                                                    updates                                                                            111 k
 libusb                                                             x86_64                                1:0.1.5-7.fc24                                                fedora                                                                              40 k
 libyaml                                                            x86_64                                0.1.6-8.fc24                                                  fedora                                                                              58 k
 oci-register-machine                                               x86_64                                0-3.7.gitbb20b00.fc25                                         updates                                                                            954 k
 oci-systemd-hook                                                   x86_64                                1:0.1.7-1.git1788cf2.fc25                                     updates                                                                             32 k
 policycoreutils-python-utils                                       x86_64                                2.5-20.fc25                                                   updates                                                                            217 k
 policycoreutils-python3                                            x86_64                                2.5-20.fc25                                                   updates                                                                            1.8 M
 python                                                             x86_64                                2.7.13-2.fc25                                                 updates                                                                             96 k
 python-backports                                                   x86_64                                1.0-8.fc25                                                    fedora                                                                              10 k
 python-backports-ssl_match_hostname                                noarch                                3.5.0.1-3.fc25                                                fedora                                                                              18 k
 python-chardet                                                     noarch                                2.3.0-1.fc25                                                  fedora                                                                             233 k
 python-ipaddress                                                   noarch                                1.0.16-3.fc25                                                 fedora                                                                              39 k
 python-libs                                                        x86_64                                2.7.13-2.fc25                                                 updates                                                                            6.2 M
 python-markupsafe                                                  x86_64                                0.23-10.fc25                                                  fedora                                                                              35 k
 python-pip                                                         noarch                                8.1.2-2.fc25                                                  fedora                                                                             1.7 M
 python-six                                                         noarch                                1.10.0-3.fc25                                                 fedora                                                                              35 k
 python-websocket-client                                            noarch                                0.37.0-2.fc25                                                 fedora                                                                              62 k
 python2-babel                                                      noarch                                2.3.4-2.fc25                                                  fedora                                                                             4.9 M
 python2-docker                                                     noarch                                2.1.0-1.fc25                                                  group_ansible-service-broker-ansible-service-broker                                166 k
 python2-docker-pycreds                                             noarch                                0.2.1-2.fc25                                                  fedora                                                                              18 k
 python2-jinja2                                                     noarch                                2.8.1-1.fc25                                                  updates                                                                            554 k
 python2-pysocks                                                    noarch                                1.5.6-5.fc25                                                  fedora                                                                              25 k
 python2-requests                                                   noarch                                2.10.0-4.fc25                                                 fedora                                                                             107 k
 python2-setuptools                                                 noarch                                25.1.1-1.fc25                                                 fedora                                                                             506 k
 python2-urllib3                                                    noarch                                1.15.1-3.fc25                                                 fedora                                                                             128 k
 pytz                                                               noarch                                2016.6.1-1.fc25                                               fedora                                                                              52 k
 setools-libs                                                       x86_64                                3.3.8-12.fc25                                                 fedora                                                                             560 k
 skopeo-containers                                                  x86_64                                0.1.19-1.dev.git0224d8c.fc25                                  updates                                                                            9.6 k
 sqlite                                                             x86_64                                3.14.2-1.fc25                                                 fedora                                                                             490 k
 systemd-container                                                  x86_64                                231-15.fc25                                                   updates                                                                            412 k
 yajl                                                               x86_64                                2.1.0-5.fc24                                                  fedora                                                                              37 k

Transaction Summary
=================================================================================================================================================================================================================================================================
Install  40 Packages

Total download size: 39 M
Installed size: 139 M
Downloading Packages:
(1/40): PyYAML-3.11-13.fc25.x86_64.rpm                                                                                                                                                                                           423 kB/s | 170 kB     00:00    
(2/40): apb-0.1.1-1.20170606172632.fc25.noarch.rpm                                                                                                                                                                                54 kB/s |  24 kB     00:00    
(3/40): python-backports-ssl_match_hostname-3.5.0.1-3.fc25.noarch.rpm                                                                                                                                                            171 kB/s |  18 kB     00:00    
(4/40): python2-docker-2.1.0-1.fc25.noarch.rpm                                                                                                                                                                                   289 kB/s | 166 kB     00:00    
(5/40): python-ipaddress-1.0.16-3.fc25.noarch.rpm                                                                                                                                                                                195 kB/s |  39 kB     00:00    
(6/40): python2-docker-pycreds-0.2.1-2.fc25.noarch.rpm                                                                                                                                                                           137 kB/s |  18 kB     00:00    
(7/40): python-websocket-client-0.37.0-2.fc25.noarch.rpm                                                                                                                                                                         184 kB/s |  62 kB     00:00    
(8/40): python2-requests-2.10.0-4.fc25.noarch.rpm                                                                                                                                                                                525 kB/s | 107 kB     00:00    
(9/40): python-six-1.10.0-3.fc25.noarch.rpm                                                                                                                                                                                       64 kB/s |  35 kB     00:00    
(10/40): libyaml-0.1.6-8.fc24.x86_64.rpm                                                                                                                                                                                         418 kB/s |  58 kB     00:00    
(11/40): python-backports-1.0-8.fc25.x86_64.rpm                                                                                                                                                                                   69 kB/s |  10 kB     00:00    
(12/40): python2-pysocks-1.5.6-5.fc25.noarch.rpm                                                                                                                                                                                 214 kB/s |  25 kB     00:00    
(13/40): python2-urllib3-1.15.1-3.fc25.noarch.rpm                                                                                                                                                                                601 kB/s | 128 kB     00:00    
(14/40): python-chardet-2.3.0-1.fc25.noarch.rpm                                                                                                                                                                                  799 kB/s | 233 kB     00:00    
(15/40): python-2.7.13-2.fc25.x86_64.rpm                                                                                                                                                                                         136 kB/s |  96 kB     00:00    
(16/40): python-pip-8.1.2-2.fc25.noarch.rpm                                                                                                                                                                                      1.5 MB/s | 1.7 MB     00:01    
(17/40): python2-setuptools-25.1.1-1.fc25.noarch.rpm                                                                                                                                                                             855 kB/s | 506 kB     00:00    
(18/40): container-selinux-2.14-1.fc25.noarch.rpm                                                                                                                                                                                305 kB/s |  32 kB     00:00    
(19/40): docker-common-1.12.6-6.gitae7d637.fc25.x86_64.rpm                                                                                                                                                                       563 kB/s |  71 kB     00:00    
(20/40): python-libs-2.7.13-2.fc25.x86_64.rpm                                                                                                                                                                                    1.6 MB/s | 6.2 MB     00:03    
(21/40): policycoreutils-python-utils-2.5-20.fc25.x86_64.rpm                                                                                                                                                                     301 kB/s | 217 kB     00:00    
(22/40): libusb-0.1.5-7.fc24.x86_64.rpm                                                                                                                                                                                          271 kB/s |  40 kB     00:00    
(23/40): policycoreutils-python3-2.5-20.fc25.x86_64.rpm                                                                                                                                                                          1.6 MB/s | 1.8 MB     00:01    
(24/40): audit-libs-python3-2.7.6-1.fc25.x86_64.rpm                                                                                                                                                                              891 kB/s |  78 kB     00:00    
(25/40): gnupg-1.4.21-1.fc25.x86_64.rpm                                                                                                                                                                                          306 kB/s | 1.3 MB     00:04    
(26/40): libsemanage-python3-2.5-9.fc25.x86_64.rpm                                                                                                                                                                               790 kB/s | 111 kB     00:00    
(27/40): setools-libs-3.3.8-12.fc25.x86_64.rpm                                                                                                                                                                                   1.0 MB/s | 560 kB     00:00    
(28/40): checkpolicy-2.5-8.fc25.x86_64.rpm                                                                                                                                                                                       416 kB/s | 297 kB     00:00    
(29/40): python-markupsafe-0.23-10.fc25.x86_64.rpm                                                                                                                                                                               370 kB/s |  35 kB     00:00    
(30/40): python2-jinja2-2.8.1-1.fc25.noarch.rpm                                                                                                                                                                                  913 kB/s | 554 kB     00:00    
(31/40): pytz-2016.6.1-1.fc25.noarch.rpm                                                                                                                                                                                         496 kB/s |  52 kB     00:00    
(32/40): libcgroup-0.41-9.fc25.x86_64.rpm                                                                                                                                                                                        416 kB/s |  67 kB     00:00    
(33/40): skopeo-containers-0.1.19-1.dev.git0224d8c.fc25.x86_64.rpm                                                                                                                                                               140 kB/s | 9.6 kB     00:00    
(34/40): sqlite-3.14.2-1.fc25.x86_64.rpm                                                                                                                                                                                         805 kB/s | 490 kB     00:00    
(35/40): oci-systemd-hook-0.1.7-1.git1788cf2.fc25.x86_64.rpm                                                                                                                                                                     308 kB/s |  32 kB     00:00    
(36/40): yajl-2.1.0-5.fc24.x86_64.rpm                                                                                                                                                                                            391 kB/s |  37 kB     00:00    
(37/40): oci-register-machine-0-3.7.gitbb20b00.fc25.x86_64.rpm                                                                                                                                                                   966 kB/s | 954 kB     00:00    
(38/40): systemd-container-231-15.fc25.x86_64.rpm                                                                                                                                                                                1.0 MB/s | 412 kB     00:00    
(39/40): docker-1.12.6-6.gitae7d637.fc25.x86_64.rpm                                                                                                                                                                              1.1 MB/s |  17 MB     00:16    
(40/40): python2-babel-2.3.4-2.fc25.noarch.rpm                                                                                                                                                                                   392 kB/s | 4.9 MB     00:12    
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                                            1.9 MB/s |  39 MB     00:21     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : python-libs-2.7.13-2.fc25.x86_64                                                                                                                                                                                                            1/40 
  Installing  : python-pip-8.1.2-2.fc25.noarch                                                                                                                                                                                                              2/40 
  Installing  : python2-setuptools-25.1.1-1.fc25.noarch                                                                                                                                                                                                     3/40 
  Installing  : python-2.7.13-2.fc25.x86_64                                                                                                                                                                                                                 4/40 
  Installing  : python-six-1.10.0-3.fc25.noarch                                                                                                                                                                                                             5/40 
  Installing  : python-websocket-client-0.37.0-2.fc25.noarch                                                                                                                                                                                                6/40 
  Installing  : python2-docker-pycreds-0.2.1-2.fc25.noarch                                                                                                                                                                                                  7/40 
  Installing  : python-ipaddress-1.0.16-3.fc25.noarch                                                                                                                                                                                                       8/40 
  Installing  : python-backports-1.0-8.fc25.x86_64                                                                                                                                                                                                          9/40 
  Installing  : python-backports-ssl_match_hostname-3.5.0.1-3.fc25.noarch                                                                                                                                                                                  10/40 
  Installing  : python-chardet-2.3.0-1.fc25.noarch                                                                                                                                                                                                         11/40 
  Installing  : python2-pysocks-1.5.6-5.fc25.noarch                                                                                                                                                                                                        12/40 
  Installing  : python2-urllib3-1.15.1-3.fc25.noarch                                                                                                                                                                                                       13/40 
  Installing  : python2-requests-2.10.0-4.fc25.noarch                                                                                                                                                                                                      14/40 
  Installing  : python2-docker-2.1.0-1.fc25.noarch                                                                                                                                                                                                         15/40 
  Installing  : python-markupsafe-0.23-10.fc25.x86_64                                                                                                                                                                                                      16/40 
  Installing  : pytz-2016.6.1-1.fc25.noarch                                                                                                                                                                                                                17/40 
  Installing  : python2-babel-2.3.4-2.fc25.noarch                                                                                                                                                                                                          18/40 
  Installing  : python2-jinja2-2.8.1-1.fc25.noarch                                                                                                                                                                                                         19/40 
  Installing  : systemd-container-231-15.fc25.x86_64                                                                                                                                                                                                       20/40 
  Installing  : yajl-2.1.0-5.fc24.x86_64                                                                                                                                                                                                                   21/40 
  Installing  : sqlite-3.14.2-1.fc25.x86_64                                                                                                                                                                                                                22/40 
  Installing  : setools-libs-3.3.8-12.fc25.x86_64                                                                                                                                                                                                          23/40 
  Installing  : skopeo-containers-0.1.19-1.dev.git0224d8c.fc25.x86_64                                                                                                                                                                                      24/40 
  Installing  : libcgroup-0.41-9.fc25.x86_64                                                                                                                                                                                                               25/40 
  Installing  : checkpolicy-2.5-8.fc25.x86_64                                                                                                                                                                                                              26/40 
  Installing  : libsemanage-python3-2.5-9.fc25.x86_64                                                                                                                                                                                                      27/40 
  Installing  : audit-libs-python3-2.7.6-1.fc25.x86_64                                                                                                                                                                                                     28/40 
  Installing  : policycoreutils-python3-2.5-20.fc25.x86_64                                                                                                                                                                                                 29/40 
  Installing  : policycoreutils-python-utils-2.5-20.fc25.x86_64                                                                                                                                                                                            30/40 
  Installing  : container-selinux-2:2.14-1.fc25.noarch                                                                                                                                                                                                     31/40 
  Installing  : libusb-1:0.1.5-7.fc24.x86_64                                                                                                                                                                                                               32/40 
  Installing  : gnupg-1.4.21-1.fc25.x86_64                                                                                                                                                                                                                 33/40 
  Installing  : docker-common-2:1.12.6-6.gitae7d637.fc25.x86_64                                                                                                                                                                                            34/40 
  Installing  : docker-2:1.12.6-6.gitae7d637.fc25.x86_64                                                                                                                                                                                                   35/40 
  Installing  : libyaml-0.1.6-8.fc24.x86_64                                                                                                                                                                                                                36/40 
  Installing  : PyYAML-3.11-13.fc25.x86_64                                                                                                                                                                                                                 37/40 
  Installing  : apb-0.1.1-1.20170606172632.fc25.noarch                                                                                                                                                                                                     38/40 
  Installing  : oci-systemd-hook-1:0.1.7-1.git1788cf2.fc25.x86_64                                                                                                                                                                                          39/40 
  Installing  : oci-register-machine-0-3.7.gitbb20b00.fc25.x86_64                                                                                                                                                                                          40/40 
  Verifying   : apb-0.1.1-1.20170606172632.fc25.noarch                                                                                                                                                                                                      1/40 
  Verifying   : python2-docker-2.1.0-1.fc25.noarch                                                                                                                                                                                                          2/40 
  Verifying   : PyYAML-3.11-13.fc25.x86_64                                                                                                                                                                                                                  3/40 
  Verifying   : python-backports-ssl_match_hostname-3.5.0.1-3.fc25.noarch                                                                                                                                                                                   4/40 
  Verifying   : python-ipaddress-1.0.16-3.fc25.noarch                                                                                                                                                                                                       5/40 
  Verifying   : python-six-1.10.0-3.fc25.noarch                                                                                                                                                                                                             6/40 
  Verifying   : python-websocket-client-0.37.0-2.fc25.noarch                                                                                                                                                                                                7/40 
  Verifying   : python2-docker-pycreds-0.2.1-2.fc25.noarch                                                                                                                                                                                                  8/40 
  Verifying   : python2-requests-2.10.0-4.fc25.noarch                                                                                                                                                                                                       9/40 
  Verifying   : libyaml-0.1.6-8.fc24.x86_64                                                                                                                                                                                                                10/40 
  Verifying   : python-backports-1.0-8.fc25.x86_64                                                                                                                                                                                                         11/40 
  Verifying   : python-chardet-2.3.0-1.fc25.noarch                                                                                                                                                                                                         12/40 
  Verifying   : python2-urllib3-1.15.1-3.fc25.noarch                                                                                                                                                                                                       13/40 
  Verifying   : python2-pysocks-1.5.6-5.fc25.noarch                                                                                                                                                                                                        14/40 
  Verifying   : python-2.7.13-2.fc25.x86_64                                                                                                                                                                                                                15/40 
  Verifying   : python-libs-2.7.13-2.fc25.x86_64                                                                                                                                                                                                           16/40 
  Verifying   : python-pip-8.1.2-2.fc25.noarch                                                                                                                                                                                                             17/40 
  Verifying   : python2-setuptools-25.1.1-1.fc25.noarch                                                                                                                                                                                                    18/40 
  Verifying   : docker-2:1.12.6-6.gitae7d637.fc25.x86_64                                                                                                                                                                                                   19/40 
  Verifying   : container-selinux-2:2.14-1.fc25.noarch                                                                                                                                                                                                     20/40 
  Verifying   : docker-common-2:1.12.6-6.gitae7d637.fc25.x86_64                                                                                                                                                                                            21/40 
  Verifying   : gnupg-1.4.21-1.fc25.x86_64                                                                                                                                                                                                                 22/40 
  Verifying   : policycoreutils-python-utils-2.5-20.fc25.x86_64                                                                                                                                                                                            23/40 
  Verifying   : libusb-1:0.1.5-7.fc24.x86_64                                                                                                                                                                                                               24/40 
  Verifying   : policycoreutils-python3-2.5-20.fc25.x86_64                                                                                                                                                                                                 25/40 
  Verifying   : audit-libs-python3-2.7.6-1.fc25.x86_64                                                                                                                                                                                                     26/40 
  Verifying   : libsemanage-python3-2.5-9.fc25.x86_64                                                                                                                                                                                                      27/40 
  Verifying   : checkpolicy-2.5-8.fc25.x86_64                                                                                                                                                                                                              28/40 
  Verifying   : setools-libs-3.3.8-12.fc25.x86_64                                                                                                                                                                                                          29/40 
  Verifying   : python2-jinja2-2.8.1-1.fc25.noarch                                                                                                                                                                                                         30/40 
  Verifying   : python-markupsafe-0.23-10.fc25.x86_64                                                                                                                                                                                                      31/40 
  Verifying   : python2-babel-2.3.4-2.fc25.noarch                                                                                                                                                                                                          32/40 
  Verifying   : pytz-2016.6.1-1.fc25.noarch                                                                                                                                                                                                                33/40 
  Verifying   : libcgroup-0.41-9.fc25.x86_64                                                                                                                                                                                                               34/40 
  Verifying   : skopeo-containers-0.1.19-1.dev.git0224d8c.fc25.x86_64                                                                                                                                                                                      35/40 
  Verifying   : sqlite-3.14.2-1.fc25.x86_64                                                                                                                                                                                                                36/40 
  Verifying   : oci-systemd-hook-1:0.1.7-1.git1788cf2.fc25.x86_64                                                                                                                                                                                          37/40 
  Verifying   : yajl-2.1.0-5.fc24.x86_64                                                                                                                                                                                                                   38/40 
  Verifying   : oci-register-machine-0-3.7.gitbb20b00.fc25.x86_64                                                                                                                                                                                          39/40 
  Verifying   : systemd-container-231-15.fc25.x86_64                                                                                                                                                                                                       40/40 

Installed:
  PyYAML.x86_64 3.11-13.fc25                   apb.noarch 0.1.1-1.20170606172632.fc25                audit-libs-python3.x86_64 2.7.6-1.fc25            checkpolicy.x86_64 2.5-8.fc25                             container-selinux.noarch 2:2.14-1.fc25         
  docker.x86_64 2:1.12.6-6.gitae7d637.fc25     docker-common.x86_64 2:1.12.6-6.gitae7d637.fc25       gnupg.x86_64 1.4.21-1.fc25                        libcgroup.x86_64 0.41-9.fc25                              libsemanage-python3.x86_64 2.5-9.fc25          
  libusb.x86_64 1:0.1.5-7.fc24                 libyaml.x86_64 0.1.6-8.fc24                           oci-register-machine.x86_64 0-3.7.gitbb20b00.fc25 oci-systemd-hook.x86_64 1:0.1.7-1.git1788cf2.fc25         policycoreutils-python-utils.x86_64 2.5-20.fc25
  policycoreutils-python3.x86_64 2.5-20.fc25   python.x86_64 2.7.13-2.fc25                           python-backports.x86_64 1.0-8.fc25                python-backports-ssl_match_hostname.noarch 3.5.0.1-3.fc25 python-chardet.noarch 2.3.0-1.fc25             
  python-ipaddress.noarch 1.0.16-3.fc25        python-libs.x86_64 2.7.13-2.fc25                      python-markupsafe.x86_64 0.23-10.fc25             python-pip.noarch 8.1.2-2.fc25                            python-six.noarch 1.10.0-3.fc25                
  python-websocket-client.noarch 0.37.0-2.fc25 python2-babel.noarch 2.3.4-2.fc25                     python2-docker.noarch 2.1.0-1.fc25                python2-docker-pycreds.noarch 0.2.1-2.fc25                python2-jinja2.noarch 2.8.1-1.fc25             
  python2-pysocks.noarch 1.5.6-5.fc25          python2-requests.noarch 2.10.0-4.fc25                 python2-setuptools.noarch 25.1.1-1.fc25           python2-urllib3.noarch 1.15.1-3.fc25                      pytz.noarch 2016.6.1-1.fc25                    
  setools-libs.x86_64 3.3.8-12.fc25            skopeo-containers.x86_64 0.1.19-1.dev.git0224d8c.fc25 sqlite.x86_64 3.14.2-1.fc25                       systemd-container.x86_64 231-15.fc25                      yajl.x86_64 2.1.0-5.fc24                       

Complete!
[root@localhost ~]# apb init -o foo bar
Initializing /root/bar for an APB.
Generating playbook files
Successfully initialized project directory at: /root/bar
Please run *apb prepare* inside of this directory after editing files.
[root@localhost ~]# cd bar
[root@localhost bar]# apb prepare
Finished writing dockerfile.

```
