### ISSUE TITLE
apb install failed with pip install

### ISSUE THREAD

**Issue by mdshuai** [fusor/ansible-playbook-bundle#35]
Test for card: https://trello.com/c/8qsYQRsB/
```
# python --version
Python 2.7.13

# pip install apb
Collecting apb
  Downloading apb-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bblqZ1/apb/setup.py", line 5, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/usr/lib/python2.7/site-packages/pip/req/req_file.py", line 84, in parse_requirements
        filename, comes_from=comes_from, session=session
      File "/usr/lib/python2.7/site-packages/pip/download.py", line 425, in get_file_content
        'Could not open requirements file: %s' % str(exc)
    pip.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: 'src/requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bblqZ1/apb/
```
system: fedora24

**Comment by mdshuai** [comment]
@dymurray help confirm, thanks

**Comment by jmrodri** [comment]
I confirmed the problem exists.

**Comment by dymurray** [comment]
@mdshuai Thank you for pointing this out. Our version in pypi was busted but should be working properly now. Please let me know if you still have problems running 'pip install apb'. I will leave this issue open for the time being until you confirm you are not seeing it on your end.

**Comment by jmrodri** [comment]
Confirmed, `sudo pip install apb` worked for me.

**Comment by mdshuai** [comment]
Confirmed, work for me, thank you.
```
# pip install apb
Collecting apb
  Downloading apb-0.1.1.tar.gz
Requirement already satisfied: PyYAML<4.0,>=3.10 in /usr/lib64/python2.7/site-packages (from apb)
Requirement already satisfied: docker<3.0.0,>=2.1.0 in /usr/lib/python2.7/site-packages (from apb)
Requirement already satisfied: websocket-client>=0.32.0 in /usr/lib/python2.7/site-packages (from docker<3.0.0,>=2.1.0->apb)
Requirement already satisfied: requests!=2.11.0,!=2.12.2,>=2.5.2 in /usr/lib/python2.7/site-packages (from docker<3.0.0,>=2.1.0->apb)
Requirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /usr/lib/python2.7/site-packages (from docker<3.0.0,>=2.1.0->apb)
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /usr/lib/python2.7/site-packages (from docker<3.0.0,>=2.1.0->apb)
Requirement already satisfied: six>=1.4.0 in /usr/lib/python2.7/site-packages (from docker<3.0.0,>=2.1.0->apb)
Requirement already satisfied: docker-pycreds>=0.2.1 in /usr/lib/python2.7/site-packages (from docker<3.0.0,>=2.1.0->apb)
Installing collected packages: apb
  Running setup.py install for apb ... done
Successfully installed apb-0.1.1
[root@dhcp-140-98 tmp]# apb --help
usage: apb [-h] [--debug] [--project BASE_PATH] {init,help,prepare,build} ...

APB tooling for assisting in building and packaging APBs.

optional arguments:
  -h, --help            show this help message and exit
  --debug               Enable debug output
  --project BASE_PATH, -p BASE_PATH
                        Specify a path to your project. Defaults to CWD.

subcommand:
  {init,help,prepare,build}
    init                Initialize the directory for APB development
    help                Display this help message
    prepare             Prepare an ansible-container project for APB packaging
    build               Build and package APB container
```
